services:
  postgres:
    image: postgres:16
    container_name: perfume
    restart: always
    environment:
      POSTGRES_DB: perfume
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  flyway:
    image: flyway/flyway:10
    container_name: flyway
    depends_on:
      - postgres
    command: -url=jdbc:postgresql://postgres:5432/perfume -user=postgres -password=postgres migrate
    volumes:
      - ./migration:/flyway/sql

  spring-app:
    build: ./ProductAPI
    container_name: product-api
    depends_on:
      - postgres
      - flyway
    ports:
      - "8090:8090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/perfume
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

volumes:
  postgres_data:
